/* eslint-disable @typescript-eslint/consistent-type-imports */

export interface MmdFrameState { readonly seconds: number; readonly frame: number; readonly frameRate: number; }
export interface MmdRuntimeDebugStageState { readonly worldMatricesColumnMajor: readonly number[]; readonly morphWeights: readonly number[]; }
export interface MmdRuntimeDebugState { readonly stages: { readonly vmdInterpolation: MmdRuntimeDebugStageState; readonly appendTransform: MmdRuntimeDebugStageState; readonly ik: MmdRuntimeDebugStageState; readonly physics: MmdRuntimeDebugStageState; }; }
export interface MmdRuntime { setAnimation(animation: import("../parser/model/modelTypes.js").MmdAnimation, mesh: import("three").SkinnedMesh): void; evaluate(seconds: number, options?: MmdRuntimeEvaluateOptions): MmdFrameState; tick(seconds: number, options?: MmdRuntimeTickOptions): MmdFrameState; /** @deprecated Use tick(seconds, { mesh, ...options }) instead. */ tick(seconds: number, mesh: import("three").Object3D | null | undefined, options?: MmdRuntimeEvaluateOptions): MmdFrameState; seek(seconds: number): MmdFrameState; resetPose(): void; clearAnimation(): void; /** @deprecated Prefer seek / resetPose / clearAnimation for finer control. */ reset(seconds?: number): MmdFrameState; frameState(): MmdFrameState; debugState(): MmdRuntimeDebugState; debugRigidBodyWorldTransformsColumnMajor?(): readonly (readonly number[])[]; }
export interface MmdRuntimeEvaluateOptions { readonly physics?: boolean; readonly ik?: boolean; }
export interface MmdRuntimeTickOptions extends MmdRuntimeEvaluateOptions { readonly mesh?: import("three").Object3D | null | undefined; }
export interface DefaultMmdRuntimeOptions { readonly frameRate?: number; readonly initialSeconds?: number; readonly physics?: "none" | "stateful-spring" | "external"; readonly physicsBackend?: import("../physics/index.js").MmdPhysicsBackend; }
export interface RuntimeRestTransform { readonly position: import("three").Vector3; readonly quaternion: import("three").Quaternion; }
export interface RuntimePhysicsData { readonly bones: readonly RuntimePhysicsBone[]; readonly rigidBodies: readonly RuntimeRigidBody[]; readonly joints: readonly RuntimeJoint[]; }
export interface RuntimeExternalPhysicsData { readonly bones: readonly RuntimeExternalPhysicsBone[]; readonly skeleton: NonNullable<import("../physics/index.js").MmdPhysicsStepContext["skeleton"]>; readonly rigidBodies: NonNullable<import("../physics/index.js").MmdPhysicsStepContext["rigidBodies"]>; readonly joints: NonNullable<import("../physics/index.js").MmdPhysicsStepContext["joints"]>; readonly morphImpulses: NonNullable<import("../physics/index.js").MmdPhysicsStepContext["morphImpulses"]>; }
export interface RuntimePhysicsBone { readonly name: string; readonly englishName: string; }
export interface RuntimeExternalPhysicsBone { readonly name?: string; readonly englishName?: string; }
export interface RuntimeRigidBody { readonly boneIndex: number; readonly mode: string; readonly size: readonly number[]; readonly mass: number; readonly linearDamping: number; }
export interface RuntimeJoint { readonly rigidBodyIndexA: number; readonly rigidBodyIndexB: number; readonly translationLowerLimit: readonly number[]; readonly translationUpperLimit: readonly number[]; readonly springTranslationFactor: readonly number[]; }
export interface RuntimeExternalRigidBody { readonly name?: string; readonly englishName?: string; readonly boneIndex: number; readonly group: number; readonly mask: number; readonly shape: "sphere" | "box" | "capsule" | "unknown"; readonly size: readonly [number, number, number]; readonly position: readonly [number, number, number]; readonly rotation: readonly [number, number, number]; readonly mass: number; readonly linearDamping: number; readonly angularDamping: number; readonly restitution: number; readonly friction: number; readonly mode: "static" | "dynamic" | "dynamicBone" | "unknown"; }
export interface RuntimeExternalJoint { readonly name?: string; readonly englishName?: string; readonly rigidBodyIndexA: number; readonly rigidBodyIndexB: number; readonly position: readonly [number, number, number]; readonly rotation: readonly [number, number, number]; readonly translationLowerLimit: readonly [number, number, number]; readonly translationUpperLimit: readonly [number, number, number]; readonly rotationLowerLimit: readonly [number, number, number]; readonly rotationUpperLimit: readonly [number, number, number]; readonly springTranslationFactor: readonly [number, number, number]; readonly springRotationFactor: readonly [number, number, number]; }
export interface RuntimeExternalMorphImpulse { readonly morphIndex: number; readonly rigidBodyIndex: number; readonly local: boolean; readonly velocity: readonly [number, number, number]; readonly torque: readonly [number, number, number]; }
export type RuntimeBoneMorphOffset = { readonly boneIndex: number; readonly translation: readonly [number, number, number]; readonly rotation: readonly [number, number, number, number]; };
export type RuntimeMorph = Pick<import("../parser/model/modelTypes.js").MorphData, "type" | "groupOffsets" | "flipOffsets"> & { readonly boneOffsets?: readonly RuntimeBoneMorphOffset[]; readonly impulseOffsets?: readonly RuntimeExternalMorphImpulse[]; };
